site_name: Igor Mkdocs Material
site_url: https://koshelekapi.github.io/mkmaterial/
repo_url: https://github.com/koshelekapi/mkmaterial
repo_name: MkMaterial
edit_uri: edit/master/docs
theme:
  name: mkdocs
  locale: en
  highlightjs: true
  hljs_languages:
      - javascript
      - html
      - xml
  navigation_depth: 4
nav:
  - First Page: '/developers-en/mainpage_en.md'