site_name: My Docs
repo_url: https://github.com/koshelekapi/mkmaterial
repo_name: koshelekapi/mkmaterial
edit_uri: docs

nav:
  - First page: docs/developers-en/mainpage_en.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences