site_name: My Docs
site_url: https://koshelekapi.github.io/mkmaterial/
repo_url: https://github.com/koshelekapi/mkmaterial
repo_name: koshelekapi/mkmaterial
edit_uri: docs

nav:
  - First page: developers-en/mainpage_en.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra:
  homepage: index.md